<a href="https://colab.research.google.com/github/sujaysathya/flight-delay-prediction/blob/master/classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
pd.set_option('display.max_columns', 130)
from sklearn import preprocessing
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score


In [0]:
le = preprocessing.LabelEncoder()
df=pd.read_csv("/content/drive/My Drive/maindataframe.csv")
dummpy_data_frame=df.copy()
df=df.iloc[:,1:31]
df.drop_duplicates(inplace=True)
y=df.ArrDel15.values
df.drop(["date","FlightDate","ArrTime","ArrDel15","ArrDelayMinutes"],axis=1,inplace=True)
df.Year=np.where(df.Year==2016,0,1)
df=pd.get_dummies(df,drop_first=True)
df["OriginAirportID"]=le.fit_transform(df.OriginAirportID)
df["DestAirportID"]=le.fit_transform(df.DestAirportID)
df["weatherCode"]=le.fit_transform(df.weatherCode)





# New Section

In [17]:

x=df
x=x.values
df.head(50)


Quarter  Year  Month  DayofMonth  DepTime  DepDel15  CRSDepTime  \
0         1     0      1           1    808.0       0.0         810   
1         1     0      1           1    810.0       0.0         812   
2         1     0      1           1    852.0       0.0         850   
3         1     0      1           1    900.0       0.0         855   
4         1     0      1           1    849.0       0.0         850   
5         1     0      1           1    821.0       0.0         825   
6         1     0      1           1    822.0       0.0         820   
7         1     0      1           1    850.0       0.0         845   
8         1     0      1           1    851.0       0.0         855   
9         1     0      1           1    815.0       0.0         810   
10        1     0      1           1    837.0       0.0         840   
11        1     0      1           2    812.0       0.0         810   
12        1     0      1           2    851.0       0.0         850   
13        1     0      1           2    819.0       0.0         820   
14        1     0      1           2    810.0       0.0         810   
15        1     0      1           2    832.0       0.0         828   
16        1     0      1           2    852.0       1.0         835   
17        1     0      1           2    905.0       0.0         855   
18        1     0      1           2    757.0       0.0         800   
19        1     0      1           2    809.0       0.0         810   
20        1     0      1           2    810.0       0.0         810   
21        1     0      1           2    908.0       0.0         855   
22        1     0      1           2    905.0       1.0         850   
23        1     0      1           2    828.0       0.0         825   
24        1     0      1           2    909.0       1.0         827   
25        1     0      1           2    836.0       0.0         829   
26        1     0      1           2    910.0       1.0         850   
27        1     0      1           2    852.0       0.0         855   
28        1     0      1           2    847.0       1.0         824   
29        1     0      1           2    901.0       1.0         840   
30        1     0      1           3    807.0       0.0         810   
31        1     0      1           3    846.0       0.0         850   
32        1     0      1           3    840.0       0.0         844   
33        1     0      1           3    755.0       0.0         800   
34        1     0      1           3    829.0       1.0         800   
35        1     0      1           3    820.0       0.0         820   
36        1     0      1           3    813.0       0.0         810   
37        1     0      1           3    808.0       0.0         810   
38        1     0      1           3    828.0       0.0         829   
39        1     0      1           3    916.0       1.0         850   
40        1     0      1           3    855.0       0.0         855   
41        1     0      1           3    831.0       0.0         824   
42        1     0      1           3    812.0       0.0         810   
43        1     0      1           3    814.0       0.0         815   
44        1     0      1           3    852.0       0.0         855   
45        1     0      1           3    850.0       0.0         850   
46        1     0      1           3    828.0       0.0         825   
47        1     0      1           3    815.0       0.0         817   
48        1     0      1           3    856.0       0.0         854   
49        1     0      1           3    840.0       0.0         840   

    DepDelayMinutes  OriginAirportID  DestAirportID  CRSArrTime  \
0               0.0                0             10        1016   
1               0.0                0              3         943   
2               2.0                0              1        1009   
3               5.0                0             10        1045   
4               0.0                0           

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 0)
y_test.shape

(185144,)

In [0]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)



In [27]:

#logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, max_iter=1200000)
classifier.fit(x_train, y_train)


# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)

print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))


[[143318   3189]
 [ 12355  26282]]
0.916043728125135
0.6802287962315915
0.8917919310508635
0.7717742409114936


In [0]:

#decision tree classifier
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)
print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))

[[134255  12252]
 [ 11394  27243]]
0.872283195782742
0.7051013277428372
0.6897835169008736
0.6973583166948242


In [0]:
#random forest classifier
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)
print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))

[[142887   3620]
 [ 11494  27143]]
0.9183662446528108
0.7025131350777752
0.8823261710496375
0.7822190201729107


In [26]:
#xgboost classifier
import xgboost as xgb
from xgboost import XGBClassifier
classifier = XGBClassifier(learning_rate =0.1,n_estimators=1000,max_depth=4,min_child_weight=6,gamma=0,subsample=0.8,colsample_bytree=0.8,reg_alpha=0.005,objective= 'binary:logistic',nthread=4,scale_pos_weight=1,seed=27)
classifier.fit(x_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)
print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))

[[143538   2969]
 [ 11841  26796]]
0.9200082098258653
0.6935321065300101
0.9002519737947253
0.7834858629864624


In [25]:

#support vector machines
from sklearn.linear_model import SGDClassifier 
classifier = SGDClassifier ()
classifier.fit(x_train, y_train)


# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)

print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))


[[138464   8043]
 [  9598  29039]]
0.9047174091517953
0.7515852680073505
0.7831023137910577
0.7670201666688679
